<?php
$users_arr=array('admin'=>'TEST_PASSWORD_123');
$config['server_timezone']='Etc/GMT';
$config['db_host']='localhost';
$config['db_login']='login';
$config['db_password']='password';
$config['db_base']='database';
$config['jsonrpc_node']='https://vizrpc.lexa.host/';
$config['infura_key']='';